export const TypeENV = Object.freeze({
  DB_HOST: 'DB_HOST',
  JWT_SECRET_ACCESS: 'JWT_SECRET_ACCESS',
  EXPIRES_IN_ACCESS: 'EXPIRES_IN_ACCESS',
  JWT_SECRET_REFRESH: 'JWT_SECRET_REFRESH',
  EXPIRES_IN_REFRESH: 'EXPIRES_IN_REFRESH',
});
